### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by MDylan** [schillermann/trolleydienst-php#1]
Hi Brothers,

Is there any plan for localization feature?
Now, all string is german, but we would like to use it an other language too.
I would recomment i18n solution for this.

Thank you!

**Comment by trolleydienst** [comment]
Yes, if you need it then you get it. ;-)

**Comment by schillermann** [comment]
Hi @MDylan,

sorry for the delay.
[Version 1.10.1](https://github.com/schillermann/trolleydienst-php/releases/tag/1.10.0) is now available with English translation.

Greetings
Mario
