### ISSUE TITLE
Optimieren für Nutzung auf Subdomain, in Unterverzeichnissen usw.

### ISSUE THREAD

**Issue by gbischmi** [schillermann/trolleydienst-php#10]
Aktuell kann trolleydienst-php nur sauber installiert werden wenn man einen eindeutigen Domain-Namen hat (welcher ist egal). Die Installation in tiefer liegende Ordner auf einem Server ist nicht vorgesehen. Installiert man das Tool in einem Unterverzeichnis funktionieren weder Images noch Css richtig, ebenso springt der Logout zurück auf die Startseite des gesamten Servers.

Eine Verbesserung dahingehend wäre sehr gut. Vielen Dank.

**Comment by trolleydienst** [comment]
Danke dir für den Hinweis.
Werde ich bei der Weiterentwicklung berücksichtigen.

Ich überlege auch die Dateien, welche von außen erreichbar sein sollen, in ein public Verzeichnis zu kopieren. Die Schwierigkeit dabei ist nur ob jeder das versteht, das Root Verzeichnis auf public zu setzen. Was meinst du dazu?

**Comment by gbischmi** [comment]
Detailfunktionen zu nutzen wird immer eine gewisse Herausforderung sein, ob das der Nutzer letztlich beherrscht kann man nicht generell absichern. Dokumentieren und dem Nutzer die Wahl lassen denke ich wäre das beste.

Danke für deine Rückmeldung 👍

**Comment by schillermann** [comment]
Die Trolleydienst App funktioniert mit der [Version 1.7.0](https://github.com/schillermann/trolleydienst-php/releases/tag/1.7.0) jetzt auch im Unterordner. Hier findest du eine [Anleitung für die Aktualisierung deiner Version](https://github.com/schillermann/trolleydienst-php/blob/1.7.0/README.md#wrench-software-aktualisieren).

**Comment by schillermann** [comment]
Ich musste noch ein paar Stellen im Code anpassen, damit Trolleydienst auch im Unterordner funktioniert.
Zusätzlich habe ich die Dateien, welche von außen erreichbar sein sollen, in den public Ordner ausgelagert.
Damit wird die Sicherheit der Anwendung erhöht.
Hier kannst du dir die [Trolleydienst Version 1.8.0](https://github.com/schillermann/trolleydienst-php/releases/download/1.8.0/trolleydienst-php-v1-8-0.zip) herunter laden.
