### ISSUE TITLE
Neue Funktionalität: Benutzer müssen von einem Admin angenommen werden um fest gebucht zu sein.

### ISSUE THREAD

**Issue by dncman** [schillermann/trolleydienst-php#14]
Wir benötigen die Funktionalität, dass Nutzer erst von einem Admin angenommen werden müssen bevor sie fest gebucht sind. 

Konkret könnte das z.B. so aussehen:
- Beliebig viele Nutzer tragen sich für eine Schicht ein und haben den Status „Beworben“.
- Der Admin nimmt nun 2 oder 3 Nutzer für eine Schicht an. Für diese ändert sich der Status auf „Angenommen“. Die restlichen Nutzer werden (nach Wunsch automatisch) abgelehnt und erhalten eine Email.
- Beworbene Nutzer sind nur für Admins sichtbar. Angenommene Nutzer sind für alle sichtbar.

Außerdem sollen normale Nutzer nur sich selbst eintragen können. Admins können weiterhin jeden Nutzer in eine Schicht eintragen und natürlich auch entfernen können.

Wir sind aktuell dabei diese Funktionalitäten in die App zu programmieren. Eventuell macht es Sinn (falls möglich/gewünscht) hier zusammenzuarbeiten.

**Comment by user-kh** [comment]
Hallo ihr Lieben,
an dieser Funktion wären wir auch sehr interessiert.
Habt ihr schon mit der Entwicklung begonnen oder ist geplant diese Funktion für alle zugänglich zu machen?

**Comment by dncman** [comment]
Hallo @user-kh , 

aktuell sind wir noch dabei den Code zu analysieren und das Design zu entwerfen. 

Sobald wir fertig sind, können wir das gerne ebenfalls auf Github laden.

**Comment by user-kh** [comment]
@dncman
Vielen Dank für eure Rückmeldung. Wir würden uns sehr freuen wenn die Funktion kommt.
Bitte denkt an uns, wenn ihr sie freigebt.
Vielen Dank

**Comment by user-kh** [comment]
Diese Funktion wird so nicht umgesetzt. Wir werden zukünftig es ermöglichen Verkündigern verschiedene Eigenschaften zuzuweisen. 
Möglichen Ideen: Auto vorhanden?, Schichtleiter, ...
