### ISSUE TITLE
Vielen Dank + Ideen, Wünsche und Fehler

### ISSUE THREAD

**Issue by user-kh** [schillermann/trolleydienst-php#15]
@schillermann
Vielen Dank für deine wertvolle Arbeit! 
Durch deinen Einsatz profitieren viele.
Echt super!
(Leider kann man dir nicht direkt schreiben, daher auf diesem Weg)

Kann man irgendwo nachlesen, welche Entwicklungen geplant sind?
(Sorry bin neu hier)

**Comment by schillermann** [comment]
https://github.com/schillermann/trolleydienst-php/issues/15

Hi @user-kh,

danke dir für dein Feedback. :blush:
Für Feedback bist du hier genau richtig.
Die Trolley Software lebt davon.

Eine Roadmap gibt es nicht.
Wo es hin gehen soll, mache ich vom Feedback abhängig, was sich die meisten wünschen.

Folgende Bereiche könnten ausgebaut werden.

### 1. Berichte Feature ausbauen
Unter dem Reiter Berichte können Berichte zu einer Trolley Schicht erstellt oder angezeigt werden. 
Man könnte das auch so umbauen, das hier die Schichten auftauchen, an denen man teilgenommen hat und hierfür den Bericht hinterlegen. Wenn der Partner dazu schon ein Bericht abgegeben hat, verschwindet die Abfrage beim Teilnehmer.
Ich weiß aber nicht ob das Feature Berichte überhabt genutzt wird. Die meisten nutzen dafür die Email oder klassisch das Papier. 
Eine Bericht Statistik wäre auch noch eine Variante.

### 2. Ansprechpartner Kontaktdaten hinterlegen
Am Kopf der Website könnte man eine Info Box anzeigen lassen, in dem man z.B. Kontaktdaten der Ansprechpartner hinterlegen kann.

### 3. Schichten als iCal Termin versenden
Wenn der Teilnehmer sich in einer Schicht eingetragen hat, bekommt er eine E-Mail als Bestätigung.
In der E-Mail könnte man eine Möglichkeit hinterlegen, mit einem Klick einen Eintrag in seinem Kalender zu hinterlegen.

### 4. Angemeldet bleiben
Beim Anmeldeformular könnte man eine Checkbox hinterlegen, so das man einen Monat lang kein Passwort mehr eingeben muss.

### 5. Zum Home Screen hinzufügen
Man könnte einen Button einblenden, mit dem die Website als App auf dem Telefon erscheint.

### 6. Unterstützung für weiter Datenbank Systeme
Es wurde auch gewünscht auf eine andere Datenbank wie Postgres oder MySql umstellen zu können.


Fallen dir noch weitere Bereiche ein, die man verbessern könnte?
Mich würde auch interessieren welche Version du nutzt?

**Comment by user-kh** [comment]
Danke für die Rückmeldung @schillermann!

Gern nehme ich dein Angebot an und möchte ich meine Vorschläge einbringen:

Vorschläge:
- [ ] Das wichtigste für uns ich die Bewerbungsfunktion so wie es @dncman vorgestellt hat
- VK bewerben sich 
- VK kann nur sich selbst bewerben
- Admin gibt diese VK erst frei 
- als Admin VK aus einer Schicht löschen
(jetzt kann man als Admin nicht mal einen VK raus nehmen - zum Beispiel wenn er krank ist)

- [ ] Musterschicht: Also nicht nur Trolley und Infostand, sondern richtige Typen:
Zum Beispiel:
- Trolley Stadt XYZ, Standard Zeit und Farbe werden beim Erstellen automatisch vorbelegt

- [ ] VK nach Name und Vorname trennen, für eine bessere Sortierung; in der Übersicht der Teilnehmer und auch wenn der Admin einen VK in eine Schicht einteilt

- [ ] Ansprechpartner Kontaktdaten hinterlegen - Die Idee find ich gut, kann ja einfach oben ein Reiter ei gefügt werden

- [ ] Responsiv Menü auf dem Handy

- [ ] Schichten als iCal Termin versenden - die Idee find ich klasse

- [ ] Angemeldet bleiben: Nicht unbedingt, ich würde eher ein Sicherheitsrisiko sehen

- [ ] Zum Home Screen hinzufügen - Klasse Idee! Lösung über Manifest und PWA

- [ ] Unterstützung für weiter Datenbank Systeme - ich weiß, dass wünschen sich viele. Als Gefahr seh ich, dass einige die Einrichtung nicht mehr schaffen. DB sqlite ist einfach und funktioniert schon auf einfachen günstigen Webservern.

Fehler:
- [ ] Übersicht der Teilnehmer ist nach ID und nicht nach Name sortiert
- [ ] Suchfunktion unter Teilnehmer klappt nicht

Wir nutzen die Version 1.9

**Comment by schillermann** [comment]
Danke dir @user-kh für die tolle Auflistung.
Den Punkt Bewerbungsfunktion werde ich als erstes angehen.
 
> Musterschicht: Also nicht nur Trolley und Infostand, sondern richtige Typen:
> Zum Beispiel: Trolley Stadt XYZ: Standard Zeit und Farbe werden beim Erstellen automatisch vorbelegt

Eine Standard Farbe könnte man in der Schichtart hinterlegen, wenn das hilft.
Den Routen Namen möchtest du auch gleich als Standard in der Schichtart?
Hab ich das so richtig verstanden?
Was meinst du mit der Standard Zeit?

**Comment by schillermann** [comment]
Über Mithilfe freue ich mich immer gerne.
Momentan stelle ich die Software auf OOP um, bevor der Ausbau der Software richtig los gehen kann.
Die funktionale Programmierung erschwert die Erweiterung und Pflege des Codes.
Es fehlt die Autocompletion in der IDE und die Funktionen sind ohne festen Zusammenhang zu einem fachlichem Bereich.

**Comment by dncman** [comment]
Auch von meiner Seite ein Dankeschön für das Erstellen und die Pflege des Projekts. 

Punkt 3, 4 und 5 klingen interessant, ist aber natürlich eher ein nice to have. Die wichtigste Funktion ist auch für uns das in #14 erwähnte Bewerbungsfeature.
Generell finde ich, dass es Sinn macht, Features über ein Art Einstellungsmenü verfügbar zu machen (für Personen die eine bestimmte Funktionalität vielleicht nicht nutzen wollen).

Ansonsten denke ich, dass das Hinzufügen mehrerer Kommentare zum Source Code von Vorteil ist, da das Verstehen des Codes dadurch erheblich erleichtert wird.

**Comment by schillermann** [comment]
@dncman die Idee mit dem Einstellungsmenü finde ich super.  :smile:
Ich werde noch ein Use Case erstellen, in dem ich eure Ideen zu der Bewerbungsfunktion aufgreife.
Wenn das Use Case von eurer Seite aus passt, setze ich es auf den Projektplan.

> Ansonsten denke ich, dass das Hinzufügen mehrerer Kommentare zum Source Code von Vorteil ist, da das Verstehen des Codes dadurch erheblich erleichtert wird.

Ja da gebe ich dir Recht. Wenn es jedoch nötig ist Kommentare zum Code hinzuzufügen, ist der Code sehr wahrscheinlich schlecht geschrieben. Das heißt also nachsitzen und ausbessern. Wenn der Code gut aufgebaut ist, erklärt er sich von selbst. Bei der Trolley Software ist auf jeden Fall Nachholbedarf, was ich momentan angehe. Mein absoluter Favorit hierfür ist [jPages](https://github.com/yegor256/jpages). Erste Schritte werde ich in kürze in einem separaten Branch veröffentlichen. :cowboy_hat_face:

**Comment by user-kh** [comment]
Hi @schillermann,
bezüglich deiner Anfrage mit den Schichten.

Wenn ich das System richtig verstanden habe, kann ich Kategorien anlegen z.B. Trolley, Infostand und "Weitere".

In den einzelnen Kategorien wäre es schön, wenn ich Muster anlegen könnte.

Ich kann ja eine Neue Schicht hinzufügen. Daneben könnte noch ein Button für Vorlagen.

Hier könnte ich ein Muster erstellen mit z.B.
* Name
* Zeit von bis
* Dauer
* Farbe

Wenn ich jetzt eine neue Schicht erstelle, habe ich ganz oben eine Drop-down-Liste mit meinen Mustern. Ich wähle eine aus und fast alles ist vorgelegt.
Zusätzlich:
Vielleicht könnte man auch noch leicht einstellen, an welchen Tagen die Schicht stattfindet und eine Serie draus machen.

_Ich hoffe man versteht mich..._

**Comment by user-kh** [comment]
@schillermann

Wenn du von jPages sprichst? Ist dann geplant, dass Backend auf Java umzustellen - also weg von PHP?

# Mithilfe
Gern binge ich mein (begrenztes) Wissen ein. 😁👍
Ich könnte mir vorstellen, dass einige hier aus dem Chat mithelfen würden.

Vielleicht besteht sogar das Interesse/ Möglichkeit sich mal über Zoom auszutauschen?> 1. Thes 5:21,22

**Comment by schillermann** [comment]
@user-kh die Software wird weiterhin komplett auf PHP aufbauen.
Ich habe mich bei jPages eher auf den Aufbau bezogen, als auf die Sprache.

Ein Treffen in Zoom ist eine tolle Idee.
Man braucht nur für alles die Zeit. :smile:
@user-kh möchtest du das ich dich zu diesem Projekt hinzufüge?

Die Zusammenarbeit könnte wie folgt ablaufen.
Unter [Discussions](https://github.com/schillermann/trolleydienst-php/discussions/categories/ideas) kann man seine Idee einreichen. Dort können die Details dazu mit allen im Team diskutiert werden. Danach wird die Discussion als Issue umgewandelt und dem Projektplan für die Umsetzung hinzugefügt.

Zur Zeit bin ich an der Umsetzung der Version 2.0 dran.
Aber es spricht nichts dagegen, wenn du eine Idee für die Version 1 hast, sie umzusetzen.
Die Änderungen kann man später in die Version 2.0 übernehmen.

**Comment by schillermann** [comment]
@user-kh zu dem [jPages Framework](https://github.com/yegor256/jpages) Beispiel habe ich bereits ein Gegenstück in PHP geschrieben, das [PhpPages](https://github.com/schillermann/phppages) heißt.
Es wird als Unterbau für die Version 2.0 dienen.

**Comment by schillermann** [comment]
@user-kh du kannst dich auch in den [Issues](https://github.com/schillermann/trolleydienst-php/issues) umschauen, ob da was für dich bei ist das du umsetzen möchtest.

**Comment by dncman** [comment]
> Ja da gebe ich dir Recht. Wenn es jedoch nötig ist Kommentare zum Code hinzuzufügen, ist der Code sehr wahrscheinlich schlecht geschrieben. Das heißt also nachsitzen und ausbessern. Wenn der Code gut aufgebaut ist, erklärt er sich von selbst.

Das wollte ich damit gar nicht ausdrücken 😅. Jeder Entwickler hat ja seinen eigenen Stil, Benamungs-Vorlieben, ... - da versteht man so manchen Teil mit Kommentaren einfach schneller. 

Bezüglich Frameworks würde es sich meiner Meinung nach ebenfalls lohnen einen Blick auf [Bootstrap](https://getbootstrap.com/), [Vue.js](https://vuejs.org/) und [Laravel](https://laravel.com/) zu werfen. Alle 3 Frameworks sind, von dem was ich gehört habe, relativ einfach zu lernen, sehr beliebt und weit verbreitet. 
Solche Frameworks sparen gerade bei der Frontendentwicklung (insbesondere bei der Mobiloptimierung) viel Zeit und machen den Code aufgrund vordefinierter Klasen/... übersichtlicher. Außerdem hat man eine breite Community und Doku die bei Problemen hilfreich sein kann.


Als zusätzliche Featureidee ist es eventuell noch hilfreich, Filter in die Schichtansicht einzufügen, z.B.:
- Zeige nur Schichten an, in denen ich eingetragen bin an
- Zeige nur Schichten an, in denen ein bestimmter User eingetragen ist an (für Admins)
- Zeige nur Schichten nach einem ausgewählten Datum an.

**Comment by user-kh** [comment]
@schillermann
Wenn du magst kannst du mich zu dem Projekt hinzufügen.
Ich will aber nicht zu hohe Erwartungen wecken 😜

Ich freue mich zu lesen, dass du schon an Version 2.0 arbeitest. 
Echt top. Vielen Dank. 


@dncman
Mit welchen Frameworks hast du schon gearbeitet/ Erfahrung?

**Comment by schillermann** [comment]
@dncman jo jeder hat sein eigenen Stil, das stimmt.
Was ich jedoch immer wieder gesehen habe ist wie wichtig ein Code ist, der ohne Ausführung des Codes von den meisten Entwicklern schnell verstanden werden kann.
Das geht aber in den Bereich Software Engineering.
Hierbei lerne ich auch immer wieder dazu.

Bootstrap ist gut um schnell was auf die Beine zu stellen, wenn man sich nicht tiefer mit CSS beschäftigen möchte.
Aber zum Glück haben wir ja schon ein schönes Layout. :sunglasses:

Vue.js ist eine schönes Framework. Ich habe auch schon überlegt das Frontend mit JavaScript zu realisieren.
Jedoch steigt mit einer weiteren Sprache der Aufwand für andere, die Software an ihre Wünsche anpassen zu können.
Und du benötigst noch eine API mit Authentifizierung.
Oder wie siehst du das?

Laravel und Symfony sind eines der am häufigsten benutzen Web Frameworks.
Wenn ich es mir einfach machen wollte und auf dem Standard aufbauen möchte, ist das eine super Wahl. :innocent:
Für die Version 2.0 ist das Ziel auf OOP umzusteigen, Laravel und Symfony sind nicht OOP und fallen daher schon raus.
Ich habe bis jetzt noch kein Web Framework gesehen, welches OOP ist.
Mit dem von dir vorgeschlagenen Framework geht es natürlich schneller.
Aber ich möchte dieses Projekt auch als Lernprojekt nutzen, um neue Möglichkeiten auszuprobieren.

Mit diesem Projekt konnte ich z.B. die funktionale Programmierung ausprobieren und bin zu dem Schluss gekommen, das je grösser ein Projekt wird, desto schwieriger ist die Weiterentwicklung.

**Comment by schillermann** [comment]
@user-kh jede Hilfe ist willkommen.
Habe dich zum Repository hinzugefügt.

**Comment by schillermann** [comment]
@dncman das sind doch tolle Vorschläge.
Möchtest du das so in der Version 1 umsetzen?

**Comment by user-kh** [comment]
@schillermann 
Danke fürs hinzufügen. 😉👍

Noch eine Fachfrage an @schillermann:
Wie lange würdest du brauchen um eine API mit Authentifizierung zu erstellen?
Bzw. Hast du schon Erfahrung damit? 


An @all könnt ihr mal schauen ob bei euch die Version 1.91 bei euch läuft.
Bei uns geht gar nichts....
🤔

**Comment by mwiefels** [comment]
@schillermann 
Vielen Dank schon mal für deine sehr gute Arbeit. Wir nutzten bisher schon das System und wollen es gerne weiterhin verwenden. Ich habe es ein wenig für unsere Zwecke angepasst. Vielleicht ist einer der 2 Punkte etwas für die offizielle Version:

**Admin´s können alle Teilnehmer wieder austragen**
Normalerweise kann man sich nur selbst austragen.

**E-Mails werden im HTML Format gesendet**
Mehr Möglichkeiten bei dem E-Mail Design. Das E-Mail Template kann ich leider nur in der Datenbank verändern. Ändere ich den HTML Code im Textfeld auf der Website löscht es den Code raus und der Plain Text bleibt. Gibt es hier eine Idee woran das liegen könnte?

**Wünsche:**
Bei vielen Schichten wäre eine andere **Ansicht** übersichtlicher. Statt einen Tag über die ganze Seitenbreite zu ziehen könnte man vielleicht 7 Tage in einer Zeile darstellen (senkrechte Kästen). Die Namen würden jeweils darunter stehen und man sieht auf großen Bildschirmen gleichen die ganze Woche.

Möchte man im nachhinein eine **Schicht** an einem vorhanden Tag hinzufügen wird sie extra dargestellt. Schön wäre, dass sie **innerhalb des vorhandenen Tages** hinzugefügt wird.

@user-kh 
Bei mir kommt der Fehler auch.

**Comment by schillermann** [comment]
Danke euch @user-kh und @mwiefels für den Hinweis, das die Database Datei fehlt.
In der Datei .gitignore wurde sie ignoriert.
Das habe ich jetzt angepasst.

[Version 1.9.2 herunter laden](https://github.com/schillermann/trolleydienst-php/releases/tag/1.9.2)

**Comment by schillermann** [comment]
> Noch eine Fachfrage an @schillermann: Wie lange würdest du brauchen um eine API mit Authentifizierung zu erstellen? Bzw. Hast du schon Erfahrung damit?

@user-kh ja ich habe schon mit einer API Authentifizierung gearbeitet.
Bei einer SPA oder Mobile App gilt grundsätzlich, trau keinem Client.
Du gibst damit einen Teil deiner Kontrolle auf dem Server nach Außen ab.
Das ist auch der Grund, warum die Authentifizierung aufwendiger wird.
Für die SPA brauchst du den [Authorization Code Flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow).

Man könnte den Teil der Authentifizierung mit einer PHP Session vereinfachen.
Mit einer Session, bist du an der gleichen Domain gebunden.
Das bedeutet das nur die SPA, welche vom gleichen Server zur Verfügung gestellt wird, Zugriff auf die API hat.

Zu einer SPA kommt noch die Sprache JavaScript hinzu.
Damit stellt sich mir die Frage, ob der Slogan der Software, mit der kinderleichten Erweiterung, noch zutrifft, wenn man eine zweite Sprache zu PHP lernen muss.

@user-kh mich würde interessieren, welche Vorteile du dir von einer API versprichst.

**Comment by schillermann** [comment]
@mwiefels das freut mich zu hören, das ihr die Software nutzt.

Magst du das Feature _Admin´s können alle Teilnehmer wieder austragen_ der Trolley Software hinzufügen?

Das Feature _E-Mails werden im HTML Format gesendet_ klinkt interessant.
Ich könnte mir vorstellen beides anzubieten.
Du kannst deswegen kein Html speichern, weil der Filter `filters\post_template_email_message.php` dies raus nimmt.
Wenn du Html in der Datenbank speichern möchtest, musst du den Filter anpassen.
Würde mich freuen, wenn du dieses Feature auch hinzufügen könntest.

Deine Wünsche sind auch toll und währen eine Bereicherung für die Trolley Software.

Bei diesem Projekt kannst du gerne direkt mitwirken, in dem ich dich als Entwickler hinzufüge, oder du machst ein Pull Request von deinem Fork Repository aus.

**Comment by user-kh** [comment]
@mwiefels: Danke deine Arbeit. Das ist ein echt tolles Feature war ihr entwickelt habt.

@schillermann:
Für die ÖZ-App braucht man keine API. Das ist wahrscheinlich mehr Arbeit wie nutzen. 

Mein Gedanke war ein anderer....
Als Versammlung hatten wir schon mal die Überlegung noch ein eigenes Planungsprogramm (Aufgaben, Einteilung, Ordnungsdienste,...) zu erstellen.
_Leider haben wir nichts passendes & fertiges gefunden._

Wichtige Anforderung wäre:
- selbst hosten
- einfach Wartung 
- Mehre Nutzer können zusammenarbeiten
- Pläne können im PDF generiert werden

Hier sehe ich den Vorteil, wenn man mit einer SPA arbeitet.
Da ich mit PHP bisher nur kleine Projekt realisiert habe, wollte ich mal von einem Fachmann wissen ob du das auch über eine API lösen würdest.
Alternativ kann man die ÖZ App so aufbohren, dass man die Funktionen integrieren kann?

**Comment by schillermann** [comment]
@user-kh verstehe, du möchtest die Trolley Software per API mit einer anderen Software verbinden.
Hab ich das so richtig verstanden?

Ein Planungsprogramm habe ich schon mal gesehen.
Die so etwas entwickeln, geben es aber nur ungern raus, da sie meist den Support Aufwand scheuen.
Aber so ein Planungsprogramm ist bestimmt auch ein tolles Projekt.

Was meinst du konkret mit _Mehre Nutzer können zusammenarbeiten_?
Meinst du das Benutzer an etwas in Echtzeit arbeiten sollen?

Eine PDF kann man doch auch mit PHP generieren, oder geht das ohne eine SPA nicht?

**Comment by user-kh** [comment]
@schillermann

Siehe
https://github.com/user-kh/JW-Versammlungsplaner/issues/1#issuecomment-1168426261

Ich hab mal ein neues R aufgemacht, damit sich niemand gestört fühlt.

**Comment by schillermann** [comment]
> **Wünsche:**
> Bei vielen Schichten wäre eine andere **Ansicht** übersichtlicher. Statt einen Tag über die ganze Seitenbreite zu ziehen könnte man vielleicht 7 Tage in einer Zeile darstellen (senkrechte Kästen). Die Namen würden jeweils darunter stehen und man sieht auf großen Bildschirmen gleichen die ganze Woche.

@mwiefels das Layout ist für die volle Breite nicht ausgelegt.
Man könnte ein neues Design einführen, wo das Menü links ist und der gesamte Bildschirm genutzt wird, wie in diesem [Beispiel Layout](https://github.com/schillermann/crm-modular-php/blob/main/dashboard.html).
Die Frage ist nur, wie das bei den anderen Benutzern ankommen wird, wenn sich das Design ändert.
Was sagen denn @geimist @dncman und @user-kh dazu?

**Comment by user-kh** [comment]
Grundsätzlich hätte ich kein Problem mit einem neuen Design.
Wenn ich es richtig verstanden habe, dann orientiert sich das Design dann an. JW Manager.

Ich denke die meisten Anwender (VK) nutzen aber ein Smartphone (also sollte das Design Moblie Frist sein)

Eine Erleichterung wäre es für die Verantwortlichen Brüder, da wahrscheinlich ein besser Überblick besteht.

@All
Ich bekomme die neue Version 1.92 nicht zum laufen. Es scheitert schon die Anmeldung.
Ich denke das hängt mit der Umstellung der Anmeldung zusammen: Benutzername oder E-Mail.
Die Spalte wird in der Datenbank nicht gefunden.
Die Update Datei fehlt aber meines Erachtens um die Datenbank anzupassen.
Könnt ihr mal schauen, ob ihr die neuste Version zum laufen bekommt!?
Danke.

**Comment by mwiefels** [comment]
> @mwiefels das freut mich zu hören, das ihr die Software nutzt.
> 
> Magst du das Feature _Admin´s können alle Teilnehmer wieder austragen_ der Trolley Software hinzufügen?
> 
> Das Feature _E-Mails werden im HTML Format gesendet_ klinkt interessant. Ich könnte mir vorstellen beides anzubieten. Du kannst deswegen kein Html speichern, weil der Filter `filters\post_template_email_message.php` dies raus nimmt. Wenn du Html in der Datenbank speichern möchtest, musst du den Filter anpassen. Würde mich freuen, wenn du dieses Feature auch hinzufügen könntest.
> 
> Deine Wünsche sind auch toll und währen eine Bereicherung für die Trolley Software.
> 
> Bei diesem Projekt kannst du gerne direkt mitwirken, in dem ich dich als Entwickler hinzufüge, oder du machst ein Pull Request von deinem Fork Repository aus.

@schillermann **Die Funktion, dass Admin´s alle austragen habe ich ganz simple gelöst. Lediglich den Code ergänzt**
`Templates/Pages/shift.php (Zeile 96)`
`<?php if($has_user_promoted || $_SESSION['is_admin']): ?>`

**Email´s in HTML zu versenden habe ich habe ich so abgeändert:**
`Modules/send_mail_plain.php (Zeile 5)`
`$headers[] = 'Content-type: text/html; charset=utf-8\r\n';`
Bin jetzt erst mal im Urlaub. Werde mir danach deinen Filter ansehen. Vielen Dank für den Tipp.

**Comment by mwiefels** [comment]
> > **Wünsche:**
> > Bei vielen Schichten wäre eine andere **Ansicht** übersichtlicher. Statt einen Tag über die ganze Seitenbreite zu ziehen könnte man vielleicht 7 Tage in einer Zeile darstellen (senkrechte Kästen). Die Namen würden jeweils darunter stehen und man sieht auf großen Bildschirmen gleichen die ganze Woche.
> 
> @mwiefels das Layout ist für die volle Breite nicht ausgelegt. Man könnte ein neues Design einführen, wo das Menü links ist und der gesamte Bildschirm genutzt wird, wie in diesem [Beispiel Layout](https://github.com/schillermann/crm-modular-php/blob/main/dashboard.html). Die Frage ist nur, wie das bei den anderen Benutzern ankommen wird, wenn sich das Design ändert. Was sagen denn @geimist @dncman und @user-kh dazu?

@schillermann Ich wäre grundsätzlich auch mit einem neuen Design einverstanden. Aber auch beim jetzigen konnte ich folgendes testen (Website Breite vergrößert):
![WhatsApp Image 2022-06-25 at 22 02 05](https://user-images.githubusercontent.com/35401693/176547954-2fbcf21e-6ef3-49d7-a342-0f51bcbca746.jpeg)
Ich habe lediglich das CSS ergänzt. Das ganze ist responsive d. h. je nach Bildschirmbreite werden maximal 7 Tage in einer Reihe angezeigt oder eben nur 1 Tag (die anderen darunter) bei sehr kleinen Bildschirmen. Aber wie gesagt... das waren gerade mal die ersten Versuche.

**Comment by schillermann** [comment]
@mwiefels tolle Idee.
Danke dir für den Screenshot.
So ist es für mich einfacher umzusetzen.

**Comment by schillermann** [comment]
Hi @mwiefels,

mit der [Version 1.10.1](https://github.com/schillermann/trolleydienst-php/releases/tag/1.10.0) können Admins nun den Teilnehmer aus der Schicht wieder austragen.

Grüße
Mario

**Comment by user-kh** [comment]
In der Datei templates/pages/password-forgot.php muss folgende Zeile ergänzt werden: <?php include '../includes/language.php' ?>

**Comment by schillermann** [comment]
@user-kh du machst es aber spannend, welche Zeile ergänzt werden muss. :smile:

**Comment by user-kh** [comment]
Github hat den Code wahrscheinlich auskommentiert.

Sorry 😅

Außerdem habe ich folgende Funktionen ergänzt:

- Wartungsmodus | Integration maintenance mode

Ich habe einen einfachen Wartungsmodus integriert. Ihr müsst nur noch in der config.php folgende Zeile ergänzen: define('MAINTENANCE', false);
So hat man die Sicherheit, dass keine Änderungen an der Datenbank vorgenommen werden solang man lokal Änderungen ausprobiert.


Weiterhin habe ich die Suche nach Teilnehmer repariert

Um den Code nicht versehentlich zu beschädigen, habe ich einen Foke erstellt.
https://github.com/user-kh/trolleydienst-php

**Comment by schillermann** [comment]
@user-kh danke dir für deine Änderungen.
Du kannst für neue Features ruhig einen Branch vom master erstellen.
Der könnte `feature/xyz` heißen.

Um einen besseren Überblick in der Entwicklung behalten zu können, sind Issues hervorragend geeignet.
Dort kann man beschreiben was man vor hat und warum das Feature nötig ist und sich zuweisen.
Damit haben alle anderen Entwickler die Möglichkeit sich dazu zu äußern.
Sobald das Feature im master Branch ist, kann das Issue geschlossen werden.
Beim merge gibt man in der commit message noch die issue id mit dem hash voran an, dann ist der commit mit dem issue verbunden.

**Comment by schillermann** [comment]
Im [Branch 2.0](https://github.com/schillermann/trolleydienst-php/blob/2.0/public/index.php) findet ihr den ersten Versuch trolleydienst auf [OOP](https://de.wikipedia.org/wiki/Objektorientierte_Programmierung) umzustellen.
Bin auf euer Feedback gespannt.

**Comment by schillermann** [comment]
Hi Alle zusammen,

wir haben gerade den [Fall](https://github.com/schillermann/trolleydienst-php/issues/13#issuecomment-1179756852) gehabt das PHPMailer in Trolleydienst eingesetzt werden sollte.
Das geht leider nicht, da [PHPMailer unter GNU Lizenz](https://github.com/PHPMailer/PHPMailer/blob/master/LICENSE) steht und das Projekt dann nicht mehr unter der [MIT Lizenz](https://github.com/schillermann/trolleydienst-php/blob/master/LICENSE) genutzt werden darf.

**Comment by schillermann** [comment]
Wenn jemand ein Vorschlag hat wie wir das am besten mit der Lizenz machen sollen, dann immer her damit.

**Comment by user-kh** [comment]
Ich hätte spontan die Idee, dass man eine Alternative verwendet.
Auf die schnelle habe ich Swift Makler gefunden. Steht unter MIT

**Comment by schillermann** [comment]
Danke dir @user-kh.
Leider wird das Projekt nicht mehr weiter geführt.
> Swiftmailer will stop being maintained at the end of November 2021.

Als Alternative wir [Symfony Mailer](https://symfony.com/doc/current/mailer.html) genannt.
Die steht sogar unter [MIT Lizenz](https://github.com/symfony/mailer/blob/6.1/LICENSE).

**Comment by user-kh** [comment]
Super, dann wäre das ja eine echte Alternative.

**Comment by S-Pfeil** [comment]
Hallo @schillermann 
mir ist aufgefallen das seit einiger Zeit die Trolleydienst-Demo nicht funktioniert. Bei klick erhalte ich nur ein weißes Fester.
Vielleicht kannst du dir das mal ansehen!

Danke für deine Arbeit!

**Comment by user-kh** [comment]
Alle Funktionen die noch gewünscht sind und umgesetzt werden soll wurden in einem seperaten Issues aufgenommen
