### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by nathan-roberts** [schillermann/trolleydienst-php#17]
Hi,

Thanks for all your hard work and for making this publicly available.

I'd like to use this for my local congregation, would you be happy if I added some simple translation and made a pull request?

Regards

Nathan

**Comment by schillermann** [comment]
Hi @nathan-roberts,

thanks for your help, but @mikecopestake created a [translation function](https://github.com/schillermann/trolleydienst-php/pull/18) already.
I will change the default language of the software to English and use it to create the next version.
I would let you know as soon as the new version is released.

**Comment by schillermann** [comment]
Hello @nathan-roberts,

[Version 1.10.1](https://github.com/schillermann/trolleydienst-php/releases/tag/1.10.0) is now available with English translation.

Greetings
Mario

**Comment by nathan-roberts** [comment]
Thanks so much, @schillermann for all your hard work and you too @mikecopestake
