### ISSUE TITLE
Fehler bei der Teilnehmer-Suche

### ISSUE THREAD

**Issue by user-kh** [schillermann/trolleydienst-php#23]
In dem Reiter Teilnehmer kann ein neuer Teilnehmer angelegt werden oder nach Teilnehmern gesucht werden.

Diese Suche funktioniert nicht.
Nach erster Einschätzung wird immer ein leerer String übertragen. Das Name Attribut (users_search) liegt auf den Button und nicht auf dem input Feld.

Außerdem werden die GET Daten nirgendwo angefragt.

Mein Vorschlag wäre die Suche mit JS umzusetzen um keine Anfrage an den Server schicken zu müssen. Man könnte eine Echtzeitsuche einbauen.

**Comment by user-kh** [comment]
Ich denke, ich konnte den Fehler beheben.

**Comment by mikecopestake** [comment]
@user-kh Do you speak English? I don't speak German I'm afraid :-(

In the past I set this up with jQuery, but if it can be done with vanilla JS that would be better. How did you implement this?

**Comment by user-kh** [comment]
Hi @mikecopestake 
my first thought was to implement the search with JS. jQuery is not necessary for this. Vanilla JS is absolutely sufficient.
Since the project is completely written in PHP, I also decided to use a PHP solution.
If you are interested in my solution then you have to replace the following three files in your code.

**Comment by schillermann** [comment]
In order to keep the project simple, it would be good if the search function runs in php.
@user-kh can you fix the problem, with the search function?

**Comment by user-kh** [comment]
@schillermann 
Schon erledigt 😉
Es müssen die drei oben genannten Datein angepasst werden.

**Comment by schillermann** [comment]
@user-kh es ist einfacher, wenn du die Änderungen selber einpflegen könntest.

**Comment by user-kh** [comment]
bug fixed in version 1.11.0
