### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by schillermann** [schillermann/trolleydienst-php#27]
Es soll möglich sein die Anwendung offline zu schalten, um Änderungen online an der Software oder Datenbank vornehmen zu können.

**Comment by schillermann** [comment]
@user-kh du hast schon mal einen guten Anfang gemacht, die Login Seite abschalten zu können.
Wenn jemand bereits eingeloggt ist, kann er trotzdem weiter arbeiten.

In der Version 2.0 werden alle Seiten aus einer Startdatei abgerufen.
Dort wird es einfacher sein die gesamte Anwendung offline zu schalten.

**Comment by schillermann** [comment]
@user-kh ich habe gerade gesehen das du in der [init_page.php](https://github.com/schillermann/trolleydienst-php/blob/master/includes/init_page.php#L12) die Session löscht und auf die Startseite leitest, wenn der Maintenance Mode aktiviert wurde.
Clever.
Da die Aufgabe komplett erfüllt wurde, kann sie nun geschlossen werden.

**Comment by mikecopestake** [comment]
@schillermann Sorry that was me, it may not be the best way of doing it, so please feel free to change it if needed.

There were a few changes that needed making to @user-kh's changes(mostly that the database table columns were different(id_user -> id, name -> first_name/last_name)

**Comment by user-kh** [comment]
@schillermann
"ich habe gerade gesehen das du in der [init_page.php](https://github.com/schillermann/trolleydienst-php/blob/master/includes/init_page.php#L12) die Session löscht und auf die Startseite leitest, wenn der Maintenance Mode aktiviert wurde."

-> Diese Ehre gebührt mir nicht... Der Code stammt nicht von mir.

**Comment by user-kh** [comment]
@mikecopestake
Yes the splat names have been changed. 
I had installed the search function in an older version.
Thank you @mikecopestakedas you have adapted the code from me!
