### ISSUE TITLE
Redesign and changes

### ISSUE THREAD

**Issue by user-kh** [schillermann/trolleydienst-php#28]
Hello friends,

I've been thinking about making small changes to the design.  These are my suggestions:

- [x] Responsive Menu
- [x] New Logo
- [x] custom css (for example: main and second color)
- [x] Filter shifts by time periods
- [x] schedule delete an show contact disconnect #29 
- [x] admin can add more Publishers to a created schedule (even if the maximum number is already reached)
- [ ] more than one shift per line (?)

What do you think?
@mikecopestake
@schillermann

**Comment by schillermann** [comment]
@user-kh that sounds good from my side.
You can create an html example page with all your suggestions, if you like.
Then we can see it in action.
The html example page can then be transferred to the software design.
I am particularly interested in how you imagined the responsive Menu.

**Comment by user-kh** [comment]
@schillermann 
You are right the menu is responsive! Simple HTML is always responsive.
I have not expressed myself correctly. I mean a hamburger menu on smaller screens.

**Comment by user-kh** [comment]
I will try to work a bit on the CSS the next days.

@schillermann 
@mikecopestake 
Another question:
Do you have in your users DB in some columns, like:
- congregation_name
- language
- note_admin
a whitespace of 1,2 teaching characters at the beginning?

**Comment by user-kh** [comment]
Hi
@mikecopestake
@schillermann
how do you like my logo idea?

![OZ Icon](https://user-images.githubusercontent.com/107541629/182040175-953e1883-72dd-4fdf-a802-e9b09d7431ac.png)

**Comment by mikecopestake** [comment]
Hi @user-kh 

I like the detail in the logo, I think it would look better as white on purple as @schillermann originally designed. Here is the logo I have been using:

![logo-trolleydienst(1)](https://user-images.githubusercontent.com/7438497/182130488-b0365dcd-751b-4eb8-b652-b37f4d6801ae.png)

I haven't had a chance to try the menu, from the code it looks good though. I will try and test it soon. Thank you!

**Comment by user-kh** [comment]
Hi
@mikecopestake
I have redesigned the logo to your suggestion. Do you like it?

![OZ Icon-weiß](https://user-images.githubusercontent.com/107541629/182204366-575b54a5-49df-423f-bfd4-55b3c33ae482.png)

**Comment by schillermann** [comment]
Both pictures are great.
Please consider that the logo is displayed small, especially as an icon in the browser tab.
The fewer details in the picture, the better you can see the picture later.

**Comment by user-kh** [comment]
Hello friends,
@schillermann
@mikecopestake 

I would like to make a suggestion to you.
How do you like the design?


![Screenshot](https://user-images.githubusercontent.com/107541629/188303871-b4616ecb-aac9-4084-b454-949a7eef814c.jpg)

**Comment by S-Pfeil** [comment]
Mein Logo sieht so aus ...
Ein Logo sollte einfach gehalten werden.
Da mit diesem Programm der Trolley-Dienst und Fernfahrer-Dienst sowie auch ein Infostand usw. geplant wird, würde ich im Logo nicht unbedingt einen Trolley verwenden.
Ebenfalls plant dieses Programm für jeden Dienstzweig einen Zeitlichen Personenkreis oder TEAM, daher stehen eigentlich die Personen im Vordergrund, was sich auch im Logo widerspiegeln sollte.
Ebenfalls finde ich, dass es besser ist eine andere Farbe zu verwenden als die JW Library, da dies ein eigenständiges System ist.
Ich habe daher folgendes Logo für mich entworfen und auch die Systemfarbe danach angepasst.

![Trolley-Planer](https://user-images.githubusercontent.com/109314541/191758596-0d9d3034-c584-4315-b16a-0bd6a723a6c0.jpg)

**Comment by user-kh** [comment]
Hi @S-Pfeil 
vielen Dank für deine Nachricht.
Dein Logo sieht sehr ansprechend aus.
(Du hast dir wirklich viele Gedanken gemacht)

Vielleicht überlegen auch andere, ob sie dein Logo verwenden dürfen. Wärst du bereit es der Community zur Verfügung zu stellen?

Ich finde deine Überlegung, das Design von der JW Library zu trennen, logisch und sehe es genauso.

Aktuell ist es ruhig geworden um das Projekt.
Vielleicht sind die meisten Anwender zufrieden mit dem Stand... und wünschen keine weiteren Anpassungen.
Mitunter haben auch einfach alle "viel um die Ohren".

Das soll einfach ein kleiner Aufruf an die Entwickler und Community zu entscheiden ob wir die App so lassen oder zu entscheiden, wo die Reise hingehen soll.

Liebe Grüße an alle ;-)

**Comment by S-Pfeil** [comment]
Hi @user-kh 
ja das Logo darf verwendet werden.
Wenn jemand Interesse hat würde ich auch eine .svg senden, da es einfach schärfer ist als .jpg

Ich benötige noch kleine Funktionen in der App, vielleicht kannst Du oder jemand anderes mir da weiterhelfen, dass wäre echt nett von Euch. 

LG

**Comment by schillermann** [comment]
Guten Abend zusammen.

@user-kh die letzte Zeit habe ich mich viel um die [Trolleydienst SPA](https://github.com/schillermann/trolleydienst-php-spa) gekümmert. In das Thema [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) habe ich mich dazu eingearbeitet. Das Grundgerüst steht soweit. Momentan füge ich die Einzelteile der SPA zusammen, die ich bereits erstellt habe. Das Layout wird sich von dieser Trolleydienst Version unterscheiden. Links wird das Menü erscheinen, welches Mobile eingeklappt werden kann. Die volle Breite des Browser Fensters wird auch genutzt. Ob wir einzelne Design Elemente von der SPA in die Trolleydienst Version übernehmen wollen können wir dann noch schauen. Danke dir auch für die Logo Erstellung.

@S-Pfeil das Logo sieht super aus. Danke dir das du uns das Logo zur Verfügung stellst. Würde mich über das SVG freuen. Hast du auch Erfahrungen mit der CSS Gestaltung?

**Comment by user-kh** [comment]
Hi @S-Pfeil 
vielen Dank, dass du das Logo zur Verfügung stellst.

Ich bin gespannt, wie die Version 2.0 von @schillermann aussieht. 
Die Anwendung soll Modular werden. Damit hätte die das Potenzial noch mehr Funktionen zu erhalten. Vielleicht könnte man sogar die Planung einer ganzen Versammlung (Aufgaben, Ordungsdienste) hierüber durchzuführen.
Das würde die Zusammenarbeit auf ein neues Level heben. 

In diesem Fall würde dein Logo gut passen, da es nicht spezifisch für das Öffentliche Zeugbisgeben wirbt. 


Du hast geschrieben, dass du noch kleinere Funktionen brauchst.
An was hast du dabei gedacht?

**Comment by schillermann** [comment]
Hi @user-kh,

modular ist eine tolle Idee.
Dann würde der Software Name Trolleydienst, aus meiner Sicht, nicht mehr passen.
Hast du einen alternativen Namen dafür?
Vielleicht JW Planer?

**Comment by user-kh** [comment]
Hi @schillermann 
hab mir auch schon gedanken gemacht:
(eigentlich würde ich am liebsten das JW nicht im Namen aufnehmen um verwechslungen zu vermeiden)

- Meeting Planner
- Versammlungsmanager (VM)
- Meeting Scheduler
- Scheduler
- Planer
- VersOrg
- JW Scheduler (gibt es schon)
- JWData

**Comment by geimist** [comment]
* ConfPlan
* CongPlan
🤷‍♂️

**Comment by S-Pfeil** [comment]
Die Frage ist ob man die Software anhand des Namen im Web finden soll?
Wenn ja, dann ist es unumgänglich auch „JW“ mit drin zu haben da, dass das Suchwort Nr.1 ist was fast jeder benutzt um im Web nach nützlicher Software zu suchen.

Meine Ideen, wenn JW mit drin sein soll ….

JW ACTIVE      
JW PIN  

oder noch kürzer

JW ON

Diese könnte man auch leicht ins Logo machen, da sie kurz sind.


Und ohne „JW“ …

PLANER
CONNECT
SEND ME

Lg

**Comment by S-Pfeil** [comment]
> Guten Abend zusammen.
> 
> @user-kh die letzte Zeit habe ich mich viel um die [Trolleydienst SPA](https://github.com/schillermann/trolleydienst-php-spa) gekümmert. In das Thema [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) habe ich mich dazu eingearbeitet. Das Grundgerüst steht soweit. Momentan füge ich die Einzelteile der SPA zusammen, die ich bereits erstellt habe. Das Layout wird sich von dieser Trolleydienst Version unterscheiden. Links wird das Menü erscheinen, welches Mobile eingeklappt werden kann. Die volle Breite des Browser Fensters wird auch genutzt. Ob wir einzelne Design Elemente von der SPA in die Trolleydienst Version übernehmen wollen können wir dann noch schauen. Danke dir auch für die Logo Erstellung.
> 
> @S-Pfeil das Logo sieht super aus. Danke dir das du uns das Logo zur Verfügung stellst. Würde mich über das SVG freuen. Hast du auch Erfahrungen mit der CSS Gestaltung?

Hallo @schillermann 
freut mich das Euch das Logo gefällt ...Erfahrung in der CSS Gestaltung habe ich leider nicht ...ich bin Anfänger was das Programmieren angeht, aber ich lerne gern dazu ...natürlich kann ich eine Website in CSS Gestalten ... aber ich glaube das kann sicher jeder der hier auf der Plattform unterwegs ist.
Sobald eine Entscheidung getroffen wurde was den Namen des Programms angeht sende ich das Logo gern als svg dann mit der richtigen Bezeichnung ;-)
lg

**Comment by user-kh** [comment]
Es simmt JW wird im Web leichter gefunden.
Trotzdem wurde aber auch die App für den Trolleydienst (Offentliches Zeugnisgeben) von euch allen gefunden.
Die Buchstaben von JW sind zwar nicht rechtlich geschützt, jedoch signalisiert das vielleicht eine Verbindung die nicht gewollt/ gewünscht ist.

Meine beiden Favoriten sind:
- Meeting Planner bzw. Planer
- PLANER (hier könnten wir sogar ein Logo gleich verwenden

Was meine die anderen?

**Comment by schillermann** [comment]
@S-Pfeil und @user-kh ihr habt beide sehr gute Gedanken.
Dann geben ich auch mal mein :brain: dazu.
Trolleydienst ist bei uns ein bekannter Begriff, mit dem die Software schnell gefunden werden kann.
Begriffe wie Meeting Planner sind sehr allgemeine Begriffe, wo ich bezweifle das die Software im Internet gefunden werden kann.
Aus meiner Sicht macht die Software keinen Sinn, wenn sie keiner findet und damit auch benutzt.
Wir können die Bezeichnung Trolleydienst auch belassen und die Software standardmäßig mit dem Modul Trolleydienst  ausliefern. Weitere Module können dann andere beisteuern.
Ich denke das einige damit ein Problem haben könnten, wenn eine sehr allgemein gehaltene Software ausgeliefert wird und man sich die Module für seine Zwecke erst einzeln zusammen suchen muss.

**Comment by schillermann** [comment]
Was meint ihr, soll [trolleydienst-php-spa](https://github.com/schillermann/trolleydienst-php-spa) auf mysql oder wie [trolleydienst-php](https://github.com/schillermann/trolleydienst-php) auf sqlite aufbauen?

**Comment by schillermann** [comment]
Hi Alle zusammen,
@user-kh das Logo vom @S-Pfeil gefällt mir auch sehr gut.
Dann würde ich mal sagen das wir dieses Logo so übernehmen.
@S-Pfeil danke dir nochmal für dein tolles Logo.

Zum Thema Module, würde ich sagen das man die offiziellen Module über meinen [Github Account](https://github.com/schillermann) laufen lassen kann und weitere Module von anderen Accounts kommen können. Wie die Module einfach in der Anwendung zugänglich gemacht werden können, müssen wir dann schauen. Wir benötigen erstmal einen Prozess für die Installation der Modulen.

**Comment by schillermann** [comment]
Ich überlege ob wir in dem Trolleydienst Modul nicht gleich die Funktion für einen Schichtenleiter einbauen.
Habt ihr Ideen wie man die bestehende Trolleydienst Anwendung dafür erweitern könnte?

**Comment by S-Pfeil** [comment]
ok, dann stellt sich nur noch die Frage ob wir es in Deutsch oder Englisch machen möchten.

1.   
![planer](https://user-images.githubusercontent.com/109314541/193406936-0c918157-90af-42bf-bdfa-0c5101595e8c.jpg)

2.
![planner](https://user-images.githubusercontent.com/109314541/193406980-97f2ec59-eb52-45be-a0e3-1e075bb46b9c.jpg)

Und nun noch einmal mit "JW" wie ich das meinte ...
3.
![jw-planner](https://user-images.githubusercontent.com/109314541/193407160-c22540ec-8103-42b5-b109-c510aeaa35f2.jpg)

Stimmt einfach ab ob 1 ... 2 oder 3 und 
ich sende dann gern die svg (die Farbe kann ja per css festgelegt werden).

Liebe Grüße

**Comment by schillermann** [comment]
Entscheidet ihr was hier am besten ist.
Eins noch zur Info.
Die Software wird auch in England eingesetzt.

**Comment by user-kh** [comment]
No. 1 😉👍

**Comment by schillermann** [comment]
Hallo Zusammen,

welche Farbe findet ihr für die Anwendung am schönsten?

Grün ...
![login-green](https://user-images.githubusercontent.com/13864946/193444906-ff45324b-888d-4c2e-8f2d-f4c01a920056.JPG)

oder Blau?
![login-blue](https://user-images.githubusercontent.com/13864946/193445005-705eabba-5f08-41d7-ada0-c81041c38da2.JPG)

**Comment by schillermann** [comment]
Grün sieht für mich schöner aus.
Blau ist immer so kalt.
Was habt ihr für Farbideen.

**Comment by user-kh** [comment]
Ich finde das grün schön.

**Comment by S-Pfeil** [comment]
grün 👍

**Comment by S-Pfeil** [comment]
nun das Logo als svg

![logo_planer_300x300](https://user-images.githubusercontent.com/109314541/193456897-973b6da8-58b5-4d5d-9e8e-5723d8da8bee.svg)

lg

**Comment by user-kh** [comment]
Coming soon 😊:
![Screenshot](https://user-images.githubusercontent.com/107541629/197393342-1702ab28-4f64-47e6-b156-634cb62dfd9c.jpg)

**Comment by user-kh** [comment]
Coming soon 😊:
![Bewerbenfunktion.jpg](https://user-images.githubusercontent.com/107541629/201857253-39c93f59-24f2-4076-b722-ad2e17667af7.jpg)

**Comment by user-kh** [comment]
Hi @schillermann und @S-Pfeil,
ich habe die neu Bewertungsfunktion hochgeladen.
Könnt ihr mal testen, ob bei euch alles geht.

Wie gefällt euch das Update?
LG

**Comment by S-Pfeil** [comment]
Nicht schlecht … bei mir läuft es super!!!
Was ich ändern würde, ist das beim Popup kein Scrollbalken erscheint, sobald die Höhe des Bildschirms zu klein wird.
Beim Filter wäre es sicher gut für den Workflow, wenn man den Filter auch einfach wieder per Button löschen kann.
Und statt „Kontakt aufnehmen mit“ würde ich es vielleicht lieber „Kontakt anzeigen von“ nennen.

Was meinst du mit „NEW Custom CSS“ ?

Danke Dir für die neuen Funktionen! 👍

**Comment by user-kh** [comment]
Hi @S-Pfeil,

erstmal danke fürs testen.
Nun zu deinen Ideen und Fragen:

**Popup kein Scrollbalken**
Kannst du mal ein Screenshot posten, damit ich genau weiß was du meist?

Wenn man den Scrollbalken unterbindet, würde es ja dazu führen dass wichtige Infos oder der Bewerbenbutton außerhalb des sichtbaren Bereichs wäre und vielleicht nicht mehr benutzt werden kann.


**Filter -> Löschen-Button**
Ja könnte man machen. Geht eigentlich auch jetzt schon, wenn man einen der beiden input Felder leer und wieder filtert.
Ich schau mal was ich machen kann. Unter Berichte hatten wir auch keinen Löschen-Button... Deswegen habe ich hier auch erstmal keinen rein gemacht.


**„Kontakt anzeigen von“ nennen.**
Gute Idee. Mach ich.


**Was meinst du mit „NEW Custom CSS“ ?**

Fasst alle Farben sind über eine Variable im CSS deklariert. Du kannst also ganz schnell das CSS an deine Farbwünsche anpassen.

**Comment by S-Pfeil** [comment]
Guten Abend @user-kh 
 
die CSS-Variable hab ich jetzt gefunden ...super Idee ...Danke!

Auf den ...**Filter -> Löschen-Button** würde ich mich sehr freuen!

**Zum Scrollbalken:** ...der entsteht wenn z.B. das Handy quer gehalten wird ...sicher findest du da auch eine Lösung ...danke schon mal!

Lg

**Comment by user-kh** [comment]
Coming soon 😊:
![Screenshot 2022-11-27 at 11-59-58 Öffentliches Zeugnisgeben - Glauchau-Ost](https://user-images.githubusercontent.com/107541629/204131791-45f00088-191d-46aa-a091-1e2d342c6034.png)

### Version 1.18.13 😀

**Was ist NEU:**

- NEW dark mode by device default
- NEW Reset date filter by Button
- NEW When you have displayed a contact you can go directly to the right shift

**Fix:**

- Popup (apply function) without scrollbar
- Translation improved
- Custom CSS improved
- Fit Date Filter

**Comment by S-Pfeil** [comment]
Hallo @user-kh 
Vielleicht noch als Info für dich.
Mir ist aufgefallen das die Farben jetzt bei allen Teilnehmern gleich sind.
Also ich meine, wenn ich als User meine Termine ansehe haben die die gleiche Farbe wie die anderen Teilnehmer. So ist es für den User nicht so leicht seine eigenen Termine schnell zu überschauen.
Vielleicht ist es aber auch von dir so gewollt. Ich habe es aber für mich wieder geändert da ich es persönlich praktischer fand.

Danke das du den "Reset" Button machst!
Dark Mode -> find ich eine super Idee 👍

**Comment by user-kh** [comment]
Hi @S-Pfeil,

ja bei mir haben alle Teilnehmer die gleichen Farben.

Aber schön, wenn du für dich eine andere Lösung gefunden hast.

Der Darkmode kann nicht manuell eingeschaltet werden. (Die Funktion wird auch nicht kommen.) Stattdessen ist er automatisch aktiv, wenn bei dem Gerät oder dem Browser der Darkmode aktiv ist. Ich Teste das derzeit bei uns. Mal schauen wie es angenommen wird.

Mich würde aber mal interessieren:
- Wieviele VK verwaltet ihr über die Software?
- Wie wird es genutzt?

Vielleicht kann man sich ja mal über Zoom austauschen?!

Was die Entwicklung betrifft, werde ich versuchen weitere kleinere Funktionen zu integrieren.
Außerdem werden Fehler behoben.

Die Entwicklung wird aber hoffentlich bald in den neuen Planer übergehen, an dem Mario schon fleißig arbeitet.
Das wird eine ganze neue Unterstützung für Versammlungen werden.
So weit die großen Pläne... Wir hoffen sehr, dass das Projekt gesegnet wird.

**Comment by S-Pfeil** [comment]
Hi @user-kh 
Bei uns kommt die Software in ca. 14 Tagen zum Einsatz.
Wir werden ca. 50 Teilnehmer in 2 Sprachen darüber koordinieren. 

Und wie es so ist … wenn die Software dann erstmal im Einsatz ist und sie übersichtlich und einfach zu bedienen ist … dann spricht sich sowas schnell rum.

- Zoomen? … ja auch keine schlechte Idee … dann mach mal en Vorschlag
- Weitere kleine Funktionen? … sind immer gut 😊 …dann informier uns hier bitte darüber!

**Was ich noch praktischer finden würde**, ist wenn man sich bewirbt oder sich aus einer Schicht entfernt …das dann der Kalender dort stehen bleibt wo der Termin eingetragen oder entfernt wurde. Und dass die „Info“ ob angenommen oder nicht als Popup erscheint und dann langsam von selbst verschwindet.
Wenn du da sofort ne Idee hast wie sowas machbar wäre, dann lass es mich gern wissen!

**Comment by user-kh** [comment]
Hi @S-Pfeil,

kannst du mal deinen Kontakt hierüber mit uns teilen:

https://fern.my-router.de:8040/index.php/s/2W9erNEHj3NsEaA

(So misst du deine Nummer hier nicht veröffentlichen)

**Comment by user-kh** [comment]
Bezüglich deiner Anfrage:

**Was ich noch praktischer finden würde...**

Diese Funktion kann man aktuell nicht umsetzen. 
Das liegt daran, dass die aktuelle Software in PHP geschrieben ist.
Solch ein UI Verhalten setzt man für gewöhnlich mit JS um.

**Comment by S-Pfeil** [comment]
Hi @user-kh
ich habe soeben das "sticky" zum Laufen bekommen.
Das Problem war in CSS -> .table-container -> overflow-x: auto; 

Also im Überblick falls jemand Interesse hat ...

Das in global.css entfernen ....
**.table-container {
    overflow-x: auto;
   }**

und das hinzufügen ...

.table th {
    padding: 10px;
    font-size: 17px;
    color: var(--withe);
	**position: sticky;
    top: 0;**
   }

...ob das eine saubere Lösung ist weiß ich nicht aber es funktioniert sehr gut 

https://user-images.githubusercontent.com/109314541/205454414-af4e925c-c24d-4560-9265-0958f478252b.mp4

**Comment by user-kh** [comment]
@S-Pfeil Super!
Vielen Dank für den Tipp.
Ich werde deinen Code noch in die nächste Version übernehmen.

(Danke auch für das Video)
