### ISSUE TITLE
Schicht löschen und Anzeige der Kontaktdaten trennen (Admin)

### ISSUE THREAD

**Issue by user-kh** [schillermann/trolleydienst-php#29]
@schillermann

Klickt man auf einen Teilnehmer einer Schicht dann werden die Kontaktdaten dieses Teilnehmers angezeigt.
Führt man die gleiche Funktion als Admin aus, wird der Teilnehmer aus der Schicht entfernt.

Wäre es sinnvoll diese Logik zu trennen und stattdessen einen Lösch-Button zu erstellen?

Vielleicht könnte man diesen hinter den Teilnehmer - Button platzieren.

**Comment by user-kh** [comment]
Your solution looks very good! Could you already test if it works?

**Comment by S-Pfeil** [comment]
Vielen Dank für den Code, so konnte ich ihn gleich einfügen und die Funktion steht sofort zur Verfügung. Das spart echt Zeit …SUPER
Ich habe diese Funktion ein wenig umgebaut, damit es auch für ältere Menschen Benutzerfreundlicher und eindeutiger ist und man sich auf dem Handy (kleines Display) nicht vertippt.
Somit wird nun nach Druck auf den „Button (GastUser)“ ein „Modal“ geöffnet, wo konkret angezeigt wird um welchen Tag / Schicht / Uhrzeit es sich handelt und eindeutig gefragt wird, was der Benutzer jetzt tun oder lassen will.
Durch dieses „Modal“ wird die ursprüngliche Ansicht nicht verkompliziert durch zusätzliche Elemente und ältere Menschen behalten den Überblick.
Sicher muss noch einiges gerade oder mittig per CSS gesetzt werden, was ich später noch machen werde.

Euch ein schönes WE !


![WhatsApp Image 2022-09-23 at 19 54 07](https://user-images.githubusercontent.com/109314541/192028565-b385345a-50e3-4717-837e-737114f1c44c.jpeg)
![WhatsApp Image 2022-09-23 at 19 54 19](https://user-images.githubusercontent.com/109314541/192028613-18c6395e-22cf-4fb5-89af-f556833b9ded.jpeg)

**Comment by schillermann** [comment]
Hallo @S-Pfeil,

auch keine schlechte Idee mit dem Popup Fenster.
@mikecopestake what do you think of the idea of the pop-up for the elderly publishers?

**Comment by user-kh** [comment]
@S-Pfeil
Könntest du deinen Code für das Modal zur Verfügung stellen?
Vielleicht kann ich dir beim CSS helfen.

Liebe Grüße

**Comment by S-Pfeil** [comment]
Hi @user-kh 
eigentlich trua ich mich gar nicht den Code zu teilen, da er noch nicht aufgeräumt ist (alles zusammen html und css), sowas mach ich immer erst zum Schluss wenn alles fertig ist und mir gefällt. Des weiteren finden sich auch noch meine eigenen Variablen drin.
Schau einfach mal ....

` <div style="background-color: #f5751f;" class="button promoted" onclick="document.getElementById('<?= $position ?><?= $id_shift ?>').style.display = 'inline-block'"> <i class="fa fa-thumbs-o-up"></i>
              <?= $name ?>
            </div>
            <div id="<?= $position ?><?= $id_shift ?>" style="display: none; position: fixed!important; top: 50%; left: 50%; transform: translate(-50%,-50%); background-color: #000000ad; padding: 20%; color: white; font-size: 20px; font-weight: 600; width: 100%; height: 100%; z-index: 1000;">
              <div style="background-color: #eeeeee; padding: 20px; justify-content: center; align-items: center; margin: 10%; border-radius: 20px; color: #4b4b4b; text-align: center;">
                <p style="margin: 20px">Dein Termin:<br>
                  <br>
                  <?= $tageKurz[date("w", $timestamp)] ?>
                  .
                  <?= $newDate ?>
                  .
                  <?= $monate[date("n", $timestamp)] ?>
                  <br>
                  Schicht:
                  <?= $position ?>
                  <br>
                  <?= $shift_time;?>
                  Uhr<br>
                  <br>
                  Möchtest du wirklich diesen Termin löschen?</p>
                <button style="margin: 10px; border: 1px solid #fe0000; width: 100px; border-radius: 5px; background-color: red" class="enable" onclick="submitForm(this)" type="button"> <i class="fa fa fa-trash-o" style="color: white;"> Löschen</i> </button>
                <div style="margin: 10px; width: 150px; border-radius: 5px; background-color: #408399; color: white;" class="button promoted" onclick="document.getElementById('<?= $position ?><?= $id_shift ?>').style.display = 'none'">NEIN </div>
              </div>
            </div>
          </form>
          <?php else: ?>
          <?php if(($shift_list['date'] === $Tagaktuell) && ($SP === $position) || ($shift_list['date'] === $Tagaktuell) && ($SP - 1 === $position)) : ?>
          <a href="./user-details.php?id_shift_type=<?= (int)$_GET['id_shift_type'];?>&id_user=<?= $id_user ?>" class="button promoted"> <i class="fa fa-info"></i>
          <?= $name ?>
          <?= $is_car ?>
          STest </a>
          <?php else: ?>
          <p href="./user-details.php?id_shift_type=<?= (int)$_GET['id_shift_type'];?>&id_user=<?= $id_user ?>" class="button promoted"> <i class=""></i>Besetzt </p>
          <?php endif ?>` 

lg SP

**Comment by user-kh** [comment]
Vielen Dank @S-Pfeil

**Comment by user-kh** [comment]
Funktion implementiert - siehe #28
