### ISSUE TITLE
Alle Namen ausblenden und nur anzeigen, wenn ...

### ISSUE THREAD

**Issue by S-Pfeil** [schillermann/trolleydienst-php#30]
Idee …
Nur Namen anzeigen von der Schicht, wo ich selber eingetragen bin, sowie von der Schicht zuvor und der Schicht danach.
Vielleicht kann mir jemand helfen?
Also was ich schon hinbekommen habe ist, dass nur mein Name angezeigt wird und sonst keine anderen Namen nur „BESETZT“ an deren Stelle. Doch wo ich selber in der Schicht eingetragen bin, werden die Namen der anderen angezeigt.
Aber es sollen auch die Namen angezeigt werden von der Schicht davor und danach egal ob ich da drin bin oder nicht, damit man sich absprechen kann. 
Doch irgendwie bekomm ich das nicht hin.
Vielleicht habt ihr einen Tipp für mich, oder noch besser einen Code?
Alles in allem sollen die Namen erst einen Tag vor Schichtbeginn sichtbar werden und beim Klick drauf auch die weiteren Infos zum Teilnehmer, aber nur für die die auch eingetragen sind. (das habe ich auch schon hinbekommen :-)

Ich wäre für eine Lösung dankbar denn dann ist das System perfekt, wie wir es uns vorstellen.
Hintergrund der Idee ist einfach, dass man auch mal mit anderen im Trolley zusammenkommt.
Wir haben damit schon gute Erfahrungen gemacht, doch das System was wir vorher hatten hat zuviel Arbeit für den Admin gemacht. 
Ich freu mich auf Vorschläge!
Danke schon mal!

**Comment by user-kh** [comment]
Hallo @S-Pfeil 
entschuldige die späte Rückmeldung,
Eine einfache Umsetzung ist nur die gleiche Schicht möglich.

Folgende Logik müsste du implementieren: 
- Wenn zwei User (id_user) in der gleichen Schicht sind (id_shift) dann wird der Name angezeigt, wenn dies nicht zutreffend ist, dann "BESETZT"

LG
