### ISSUE TITLE
Bugs in 1.11.3

### ISSUE THREAD

**Issue by BN1010** [schillermann/trolleydienst-php#31]
Hi,
in der Version 1.11.3 bin ich auf folgende Fehler gestoßen:

1. install.php
- Beim schreiben der config.php werden nicht alle Variablen korrekt übertragen. Folgende Felder sind leer: CONGREGATION_NAME; TIMEZONE; EMAIL_DISPATCH. Bei Auswahl von SMTP werden auch alle SMTP Variablen nicht übertragen (SMTP_HOST; SMTP_USERNAME; SMTP_PASSWORD; SMTP_PORT; SMTP_ENCRYPTION)
- Bei Auswahl von SMTP sollten für SMTP_ENCRYPTION außerdem entsprechende vordefinierte Optionen angeboten werden.

2. email-settings.php
- Ist noch nicht an die erweiterten (notwendigen) Inhalte der config.php angepasst. Es fehlen alle Variablen nach LOGIN_FAIL_MAX. Werden dort aktuell Einstellungen verändert und gespeichert, landet man aufgrund der fehlenden Werte im DEMO/MAINTENANCE mode.

Vielen Dank für eure Arbeit!

Ich bin zeitlich momentan leider recht eingeschränkt - könnte euch aber gemeinsam mit @dncman (siehe Issue #14) zumindest beim Testen aktueller Versionen unterstützen.

**Comment by user-kh** [comment]
Hi @BN1010 

vielen Dank für die Meldung des Fehlers.
Wir hoffe ihr habt in der Zwischenzeit eine Umgehungslösung für euer System gefunden.

Die Behebung des Fehlers wird noch etwas Zeit in Anspruch nehmen.
Sobald der Bug bereit wurde gibt es ein Update. 

Liebe Grüße

**Comment by user-kh** [comment]
Hi @BN1010, @schillermann 

könnt ihr bitrte mal den Commit #65 testen.
Klappt bei euch alles?
LG

**Comment by BN1010** [comment]
Hi @user-kh,
sorry - erst jetzt dazu gekommen. Sieht gut aus. Bei mir läuft alles.

**Comment by user-kh** [comment]
Danke für die Rückmeldung @BN1010.
Ich versuche die Tage noch die email-settings.php anzupassen.

Dann gibt es ein neues Release.
LG

**Comment by user-kh** [comment]
Hi @BN1010,
ich habe die restlichen Funktionen noch implementiert.
Eine neue Version ist verfügbar.

Viel Freude damit.
@schillermann Ich denke wenn aus deiner Sicht keine Fehler sind können wir den Issue schließen.

LG

**Comment by schillermann** [comment]
@user-kh haste sehr schön umgesetzt.
Super Arbeit.
