### ISSUE TITLE
Problem beim installieren

### ISSUE THREAD

**Issue by lukasblacha** [schillermann/trolleydienst-php#47]
Hallo,

ich habe auf meinem V-Server das Problem, dass ich die Installation nicht erfolgreich abschließen kann...

Infos zum Server:
- Ubuntu Server 22.04.2 LTS
- Apache2 Web-Server
- PHP8.1

Die Fehlermeldung die ich erhalte:
Database connection failed: SQLSTATE[HY000] [14] unable to open database file

Dieses Problem bekomme ich in der aktuellsten Version und der Version davor.

Gruß
Lukas

**Comment by BN1010** [comment]
Hi Lukas, 
diese Fehlermeldung deutet aus meiner Sicht auf eine unzureichende Rechtevergabe hin.
Du solltest überprüfen, ob für das DB file ausreichende Lese-/Schreibrechte vergeben sind.

Gruß
Ben

**Comment by lukasblacha** [comment]
Hey Ben,
ich habe dem Verzeichnis /var/www/html und dann dessen Unterverzeichnissen alle Rechte mit chmod 777 vergeben.
Also einen Freifahrtsschein... sollte man nicht machen... aber zu Testzwecken denke ich ist das OK.

Fazit... geht leider immer noch nicht :/

LG
Lukas

**Comment by BN1010** [comment]
Versuch mal die Owner/Group ID auf 33 zu setzen und chmod 644 sollte reichen.

**Comment by BN1010** [comment]
Demzufolge ist der SQLSTATE Fehler aber gelöst?
Was sagt denn deine Logdatei bei welchem Zugriff der 403 entsteht?

**Comment by lukasblacha** [comment]
Leider nein...
Das sagt der Log:

```
[Wed Mar 22 10:30:53.279931 2023] [php:warn] [pid 27289] [client x.x.x.x:48910] PHP Warning:  require(../includes/language.php): Failed to open stream: Permission denied in /var/www/html/public/install.php on line 2
[Wed Mar 22 10:30:53.279999 2023] [php:error] [pid 27289] [client x.x.x.x:48910] PHP Fatal error:  Uncaught Error: Failed opening required '../includes/language.php' (include_path='.:/usr/share/php') in /var/www/html/public/install.php:2\nStack trace:\n#0 {main}\n  thrown in /var/www/html/public/install.php on line 2
[Wed Mar 22 10:30:59.950578 2023] [php:warn] [pid 27305] [client x.x.x.x:48912] PHP Warning:  require(/var/www/html/public/../vendor/autoload.php): Failed to open stream: Permission denied in /var/www/html/public/index.php on line 10
[Wed Mar 22 10:30:59.950639 2023] [php:error] [pid 27305] [client x.x.x.x:48912] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/public/index.php:10\nStack trace:\n#0 {main}\n  thrown in /var/www/html/public/index.php on line 10

```

**Comment by BN1010** [comment]
Das DB Problem ist gelöst. Aber offenbar hast du weiterhin unzureichende Berechtigungen für die im Log angegebenen Dateien/Ordner.
