### ISSUE TITLE
Standard-Farbe pro Schichtart

### ISSUE THREAD

**Issue by user80333Q** [schillermann/trolleydienst-php#5]
Im Stand 1.5 lassen sich die Schichtarten definieren. Schön wäre dazu wenn man eine "Standard-Farbe" pro Schichtart dort definieren könnte. Bisher kann man das nur an jeder Schicht einzeln umstellen - das kann auch so bleiben, sollte aber aus der Vorgabe so schon kommen.

Mal ein Beispiel:

Schichtarten

- Trolley Stadt (lila)
- Infostand (blau)
- Trolley Bahnhof (dunkelrot)

für besondere Einsätze in diesen angelegten Schichtarten kann dann ja trotzdem fallweise die Farbe noch umgestellt werden um eine bestimmte Schicht anders hervor zu heben.

**Comment by gbischmi** [comment]
Im Vergleich zum "alten" trolleydienst - ist es in trolleydienst-php ja schön gelöst das man unterschiedliche Seiten/Register für die Dienste getrennt hat. Früher war das eine Liste.

Die Farben haben früher jedoch die Schichtart deutlich gekennzeichnet - das fehlt jetzt bzw. muss man für jede Schicht wieder neu von Hand einstellen. Klar könnte man sagen wenn man Trolley anklickt ist alles klar - aber die Farbe hat gegen Verwechslung geschützt.

Und - evtl. noch problematischer - es fehlt jetzt das Berechtigungssystem, Wer darf eigentlich welche Schichtart sehen oder sich dafür eintragen. Jeder darf einfach alles.

**Comment by user-kh** [comment]
siehe #45 
Diese Funktion wird zukünftig umgesetzt.
