### ISSUE TITLE
Berechtigungen pro Schichtart

### ISSUE THREAD

**Issue by user80333Q** [schillermann/trolleydienst-php#6]
In den Teilnehmern fehlen seit dem neuen Release (1.4/1.5) des Trolleydienst die Vergabe / Einschränkung für die Dienstzweige / Schichtarten.

Kommt die Funktion wieder rein? Wäre für uns wichtig, da die VK sich nur für Schichten bewerben sollen (und sehen sollen) für die eine Schulung besucht wurde. Die alte Einteilung Ja / Schulung / Nein war insofern nicht schlecht.

Die Berechtigung sollte auch im Teilnehmer zu setzen sein wie bisher - in dem Zusammenhang müsste dann aber auch auf die selbst definierbaren Schichtarten zurück gegriffen werden. Wenn es zu viel Aufwand bedeutet unterschiedliche Schichtarten mit Berechtigung im Teilnehmer zur Pflege anzubieten sollte man sie dort wenigstens sehen können wenn der Teilnehmer aufgerufen wird. Die Pflege/Zuordnung der VK könnte man ja auch über die Schichtart machen wenn man dort auf der Unterseite jeder Schichtart dann alle aktiven VK zum "anhaken" bekommt. Ein generelles "Aktivieren" oder "Deaktivieren" sollte es auch geben wenn sich mal eine Schichtart komplett ändert.

**Comment by user-kh** [comment]
Diese Funktion wird so nicht umgesetzt. Wir werden zukünftig es ermöglichen Verkündigern verschiedene Eigenschaften zuzuweisen.
