### ISSUE TITLE
Email Benachrichtigung (Schicht Termin)

### ISSUE THREAD

**Issue by mwiefels** [schillermann/trolleydienst-php#8]
Trägt man sich in eine Schicht ein wird einem per Email die 1. Schicht des Tages zugeschickt.
Ganz egal um welche Uhrzeit man sich einträgt werden immer die Uhrzeiten der 1. Tagesschicht angezeigt.

Könntest du das bitte auf die richtige Uhrzeit abändern.

Vielen Dank im Voraus.

**Comment by schillermann** [comment]
Ist in der [Version 1.9.1](https://github.com/schillermann/trolleydienst-php/releases/tag/1.9.1) behoben.
