### ISSUE TITLE
Datenbankanbindung wecheln

### ISSUE THREAD

**Issue by J833hapTe16** [schillermann/trolleydienst-php#9]
Wird es möglich sein eine andere Datenbank anzubinden? MySQL oder Postgre?

Gibt es da vielleicht schon ein Template-File und angepasste Konfigurationsdatei?

Wäre dann einfacher zentral die Daten getrennt von der Anwendung zu sichern oder mit anderen Systemen zu koppeln.

**Comment by schillermann** [comment]
Danke dir für dein Feedback.

Ich werde mir dazu Dbal anschauen, ob das noch performant genug ist, im Gegensatz zu reinem SQL.
Damit könnte man die Datenbank Engine leichter wechseln.
Eine andere Variante wäre unterschiedliche SQL Befehle pro Datenbank Engine zu schreiben.
Bei Sqlite, Postgres und MySQL wären das schon 3 mal so viele SQL Befehle.

**Comment by schillermann** [comment]
Hi @J833hapTe16,

ich bereite schon mal alles für ein optionales [Wechseln der Datenbank](https://github.com/schillermann/trolleydienst-php/issues/21) von Sqlite zu MySQL vor.

**Comment by schillermann** [comment]
Hi @J833hapTe16,

Dbal werden wir in dem Projekt nicht verwenden, da Doctrine zu viel aufblähen würde.
Ohne Doctrine müssten SQL Befehle pro Datenbank Engine geschrieben werden, was ebenfalls einen Mehraufwand bedeutet.
Die Entwicklung wird von einem kleinem Team betreut, daher reicht die Zeit nicht die Software für mehrere Datenbank Engines zu erweitern.
